### ISSUE TITLE
Some thoughts on Lecture 3

### ISSUE THREAD

**Issue by khwilson** [uo-ec607/lectures#10]
I was looking through your shell slides and they are awesome!!!

As I was reading I had a couple comments, which are below. Feel free to ignore (some of these are stylistic). Thanks again for posting these slides!

* I find it important to know that in a man page /term will search for term.
* You might want to suggest single quotation marks when suggesting quoted names or else people will get confused when special symbols end up breaking things (eg in your sed commands you use single quotes)
* On slide 36 /n should be \n
* Not sure you want to bring it up, but head and tail also have a character mode that is often useful for files with long lines (head -c 1000)
* In a bit of a pain that always comes up when I teach this stuff: Mac installs the BSD utilities instead of GNU utilities. So if people start exploring grep and sed, they’re probably going to hit issues pretty quick https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed

**Comment by grantmcdermott** [comment]
These are all great, thanks Kevin. 

I'll add 'em in shortly.
