### ISSUE TITLE
Broken link on slide 42 of lecture 5

### ISSUE THREAD

**Issue by beeb22** [uo-ec607/lectures#13]
The twitter link to the 'long-running joke' about Stata's reshape command no longer works (Scott Imberman seems to have changed his handle and deleted past tweets?). The link's on slide 42 of lecture 5.

Thank you for sharing these materials: it's hugely appreciated!

**Comment by beeb22** [comment]
And a typo on slide 45: should be 'occurrence', not 'occurence' !

**Comment by beeb22** [comment]
A few more tiny things:
the 'web ettiquette' header in lecture 6 should be 'etiquette';
it should be 'your new FRED API key', not 'you're new FRED API key', in the API keys section of lecture 7;
it should be 'data acquisition', not 'data aquisition', in the 3rd application section of lecture 7;
footnote 4 of lecture 7 should be 'R *is* ideally suited', not 'R ideally suited'.
These are so so minor - I hope pointing them out is more useful than annoying. A slightly less minor point is that I don't think the 'fredr' package is in the CRAN repository any more: it seems only to be available on github (I got it by running 
```
devtools::install_github("jcizel/FredR")
```

Thank you, again, for sharing these lectures. They're incredibly helpful.

**Comment by grantmcdermott** [comment]
Much appreciated! (You can tell that I originally wrote these notes before RStudio included the built-in spell-checker...)

FWIW, I haven't incorporated all your suggestions b/c I've already adjusted them in the notes for the [sister course](https://github.com/uo-ec510-2020-spring/lectures) to this one. But I still need to decide the best way to reconcile the diffs and port them over here.
