### ISSUE TITLE
Parallelization, furrr, and future

### ISSUE THREAD

**Issue by edrubin** [uo-ec607/lectures#3]
I could be wrong, but I think you need update the seed setting for `furrr` and `future` (`future.apply`) functions. `furrr` functions want an additional argument `.options = future_options(seed = T)`, and `future` (`future.apply`) functions want a similar argument `future.seed = T`.

**Comment by grantmcdermott** [comment]
Thanks @edrubin, you're quite right. (Finally getting around to looking at this now!) Will update the notes.
