### ISSUE TITLE
Typos on title of slides 42-43 of lecture 2 (Git)

### ISSUE THREAD

**Issue by pamdx** [uo-ec607/lectures#8]
Hi,

Many thanks for making this amazing course public, I'm learning a lot! I just wanted to point out that you titled slides 42-43 of your second lecture ".gitgnore" (you missed the second "i"). I thought maybe it could be misleading in some situations.

Best,

Pierre

**Comment by pamdx** [comment]
Another typo, on slide 46: "Create a repo on GitHub and initiaize [you missed the "l"] with a README."

**Comment by grantmcdermott** [comment]
Gotcha. Thanks!
